# Project definitions
self_path: null # for programmatic updating
video_path: null
segmentation_type: 2d

# Preprocessing
preprocessing_config: config/preprocessing_config.yaml

# Data
dataset_params:
  start_volume: 0
  num_frames: 1
  num_slices: 33

# Segmentation
segmentation_params:
  stardist_model_name: lukas

# Postprocessing
postprocessing_params:
  upper_length_threshold: 12
  lower_length_threshold: 3
  to_remove_border: false
  border_width_to_remove: 0
  to_remove_dim_slices: true

# Output
output:
  folder: null # Default creates a folder within the data folder
  masks: masks.zarr
  metadata: metadata.pickle

# Printing
verbose: 1
DEBUG: false
