
# Global requirement
project_dir: "/scratch/neurobiology/zimmer/path/to/this/project"
code_path: "/scratch/neurobiology/zimmer/wbfm/code/wbfm/wbfm/scripts"

# Step 0: preprocessing
# Also uses raw data and produces a .zarr.zip, but that will NOT be within this project, so is not included
output_0:
  - dat/bounding_boxes.pickle

# Step 1: segmentation
# NOTE: raw data is outside the project, and thus is not in this format
input_1:
  - dat/bounding_boxes.pickle
output_1_dir:
  - 1-segmentation/masks.zarr
output_1:
  - 1-segmentation/metadata.pickle

# Step 2: tracklets
input_2a_dir:
  - 1-segmentation/masks.zarr
input_2a:
  - 1-segmentation/metadata.pickle
output_2a:
  - 2-training_data/raw/frame_dat.pickle

input_2b_dir:
  - 1-segmentation/masks.zarr
input_2b:
  - 1-segmentation/metadata.pickle
  - 2-training_data/raw/frame_dat.pickle
output_2b:
  - 2-training_data/raw/match_dat.pickle

input_2c:
  - 2-training_data/raw/frame_dat.pickle
  - 2-training_data/raw/match_dat.pickle
output_2c:
  - 2-training_data/all_tracklets.pickle
  - 2-training_data/raw/clust_df_dat.pickle

# Step 3: Tracking
input_3a:
  - 1-segmentation/metadata.pickle
  - 2-training_data/raw/frame_dat.pickle
output_3a:
  - 3-tracking/postprocessing/df_tracks_superglue.h5

input_3b:
  - 3-tracking/postprocessing/df_tracks_superglue.h5
  - 2-training_data/all_tracklets.pickle
output_3b:
  - 3-tracking/postprocessing/combined_3d_tracks.h5
  - 3-tracking/global2tracklet.pickle

# Step 4: final traces
input_4:
  - 3-tracking/postprocessing/combined_3d_tracks.h5
  - 1-segmentation/metadata.pickle
output_4:
  - 4-traces/all_matches.pickle
  - 4-traces/red_traces.h5
  - 4-traces/green_traces.h5
output_4_dir:
  - 4-traces/reindexed_masks.zarr.zip
