---
# Project definitions
video_path: null
segmentation_type: 2d

# Preprocessing
preprocessing_config: segmentation/preprocessing_config.yaml

# Data
dataset_params:
  start_volume: 0
  num_frames: 1
  num_slices: 33

# Segmentation
segmentation_params:
  stardist_model_name: lukas

# Postprocessing
postprocessing_params:
  upper_length_threshold: 12
  lower_length_threshold: 3
  to_remove_border: true
  border_width_to_remove: 100

# Output
output_params:
  output_folder: segmentation

# Printing
verbose: 1
DEBUG: false
